### ISSUE TITLE
Streaming sync - complete the server-side work

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_client_sdk#411]
**Describe the bug**
* Local updates made before initial sync is complete do not sync to the cloud secondary server
* Initial sync does not appear to be triggered immediately upon creation of AtClientManager (or switching to another @ sign)
* Sync runs periodically. As a result it can be up to 5 seconds before an update (e.g. creating a new key) is synced to the cloud secondary server. Developer expectation would be that local updates are streamed to the server is near-real-time when there is connectivity

**Expected behavior**
* If local mutations to keystore should not be permitted before initial sync is complete, then those mutations should be inhibited
* Sync should commence immediately upon creation of AtClientManager or switching atsign
* Sync should always be happening, in near-real-time in both directions, when there is connectivity

**Comment by gkc** [comment]
There are multiple engineer-weeks of work required here. Sprint estimates should be "how much do we want to invest in this sprint" rather than "how much work will this take"

**Comment by murali-shris** [comment]
@srieteja please update this ticket with changes you are currently working on

**Comment by srieteja** [comment]
The above-mentioned PR makes sync params available to the developers to configure as required. I tested it by setting values 1, 1, 1(syncRequestTriggerInSeconds, syncRequestThreshhold, syncRunIntervalInSeconds) and the values were being synced by the next second as expected. This should solve the real-time sync requirement.

**Comment by gkc** [comment]
I'll be working on this over the next couple of days

**Comment by gkc** [comment]
Lots of progress; needs another 2-3 days to make sure all functionality and error handling is fully covered by tests

**Comment by gkc** [comment]
LOL Gary-from-the-past "2-3 days"

Burned another 8SP in sprint PR33

Server-side looks pretty solid. Client side seems solid but I still don't have enough coverage of all of the edge cases in order to be sure.

**Comment by gkc** [comment]
No progress this past sprint, all time spent on Atmosphere Pro work and the Java client library MVP. Will be my primary focus in PR35

**Comment by gkc** [comment]
No progress in PR35; my time was spent on the Java client library and on eliminating end-to-end notification latency

Time-boxing to 5 SP for sprint 36

**Comment by gkc** [comment]
Create a new issue #504 for continued work. Updated story points burned so far on this for posterity
